### what is Numpy array
numpy stands for numeric python and it is a core library for numeric and scientific computing 

1*n one dimensional

n*n multidimensional

In [1]:
import numpy as np
a = np.array([1,2,3,4])

In [3]:
type(a)

numpy.ndarray

n Python, ndarray stands for "N-dimensional array", which is a data structure used 
to store and manipulate multidimensional arrays of homogeneous data.

ndarray is a fundamental object in the NumPy library, 
which is a powerful tool for scientific computing and data analysis in Python.
It provides efficient algorithms for performing mathematical operations on large 
arrays and matrices of numerical data.

An ndarray is a collection of elements of the same data type (e.g., integers, floats, etc.) 
arranged in a multidimensional grid. The number of dimensions and the size of each dimension
are specified when the array is created, and each element in the array can be accessed using 
its index.

ndarray is similar to a list in Python, but it is much more efficient for numerical computations
involving large amounts of data. It also provides many built-in functions for manipulating and
analyzing arrays, such as linear algebra operations, statistical functions, and image processing
functions.







In [4]:
ar = np.array([[1,2,3],[2,34,5]])

In [5]:
ar

array([[ 1,  2,  3],
       [ 2, 34,  5]])

In [6]:
n1 = np.zeros((2,3))
n1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
n1 = np.full((2,2),5)
print(n1)

[[5 5]
 [5 5]]


In [10]:
n1 = np.arange(10,51,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [12]:
n1 = np.random.randint(10,100,10)
print(type(n1))
print(n1)

<class 'numpy.ndarray'>
[96 21 67 74 33 88 91 33 35 53]


In [13]:
n1.shape 

(10,)

In [14]:
n1 = np.array([[1,2,3],[3,4,5]])
n1.shape

(2, 3)

NumPy is faster than a list in many cases because of the
way it handles data. NumPy arrays are designed to be homogeneous, 
meaning that all elements of the array are of the same type. 
This allows NumPy to optimize its operations for a specific data type, 
resulting in much faster computation times.

In contrast to NumPy arrays, lists are not stored in contiguous blocks of memory. Instead, a list is a collection of pointers to objects, where each pointer points to the location of the corresponding object in memory. This means that accessing or manipulating elements in a list requires following a series of pointers, which can be slower than accessing elements in a NumPy array.


So when we access the third element of the list using my_list[2], Python first looks up the memory location of the third element using the pointer stored in the list, and then follows that pointer to the actual memory location where the integer object is stored.

This series of pointer dereferencing can add extra overhead when accessing elements in a list, especially for large lists or when many elements need to be accessed or manipulated. In contrast, NumPy arrays use contiguous blocks of memory, so accessing elements in an array can be faster since there is no need to follow a series of pointers

n contrast, a list can contain elements of different data types, which makes it less efficient for certain types of computations. Additionally, NumPy arrays are stored in contiguous blocks of memory, which allows for faster access and manipulation of the data.

Overall, the combination of homogeneous data, contiguous memory layout, and optimized functions makes NumPy faster than a list for numerical computations. However, for more general-purpose tasks that do not involve numerical computations, a list may be more suitable.

#### PRACTICAL USE OF NUMPY ARRAY

Suppose you have a dataset containing the monthly sales data of a company for the past year, where each row represents a month and each column represents a product category. You want to perform the following tasks:

Calculate the total sales for each product category.
Find the month with the highest total sales.
Compute the average sales for each month.

In [15]:
import numpy as np
dat = np.loadtxt('C:/Users/pawar/Videos/data.txt',delimiter=',')
dat

array([[100., 200., 150., 250.],
       [150., 250., 200., 300.],
       [200., 300., 250., 350.],
       [250., 350., 300., 400.],
       [300., 400., 350., 450.],
       [350., 450., 400., 500.],
       [400., 500., 450., 550.],
       [450., 550., 500., 600.],
       [500., 600., 550., 650.],
       [550., 650., 600., 700.],
       [600., 700., 650., 750.],
       [700., 800., 750., 850.],
       [100., 200., 150., 250.],
       [150., 250., 200., 300.],
       [200., 300., 250., 350.],
       [250., 350., 300., 400.],
       [300., 400., 350., 450.],
       [350., 450., 400., 500.],
       [400., 500., 450., 550.],
       [450., 550., 500., 600.],
       [500., 600., 550., 650.],
       [550., 650., 600., 700.],
       [600., 700., 650., 750.],
       [700., 800., 750., 850.],
       [400., 500., 450., 550.],
       [450., 550., 500., 600.],
       [500., 600., 550., 650.],
       [550., 650., 600., 700.],
       [600., 700., 650., 750.],
       [700., 800., 750., 850.],
       [55

In [16]:
a = np.sum(dat,axis=0)
a

array([14150., 17450., 15800., 19100.])

#### axis = 0 meaning column || axis = 1 meaning row

In [17]:
avg_sales = np.mean(dat, axis=0)

In [18]:
avg_sales

array([428.78787879, 528.78787879, 478.78787879, 578.78787879])

In [19]:
dat.shape

(33, 4)

In [22]:
max_sales_month = np.argmax(np.sum(dat, axis=1))

In [23]:
max_sales_month

11

In [27]:
a = dat[11]

In [28]:
a

array([700., 800., 750., 850.])

In [29]:
import numpy as np

dat = np.loadtxt('C:/Users/pawar/Videos/data.txt', delimiter=',')

# Create an index column using np.arange and reshape it to be a column vector
index_col = np.arange(dat.shape[0]).reshape((-1, 1))

# Concatenate the index column and the dat array along the second axis (axis=1)
dat_with_index = np.concatenate((index_col, dat), axis=1)

# Print the result
print(dat_with_index)

[[  0. 100. 200. 150. 250.]
 [  1. 150. 250. 200. 300.]
 [  2. 200. 300. 250. 350.]
 [  3. 250. 350. 300. 400.]
 [  4. 300. 400. 350. 450.]
 [  5. 350. 450. 400. 500.]
 [  6. 400. 500. 450. 550.]
 [  7. 450. 550. 500. 600.]
 [  8. 500. 600. 550. 650.]
 [  9. 550. 650. 600. 700.]
 [ 10. 600. 700. 650. 750.]
 [ 11. 700. 800. 750. 850.]
 [ 12. 100. 200. 150. 250.]
 [ 13. 150. 250. 200. 300.]
 [ 14. 200. 300. 250. 350.]
 [ 15. 250. 350. 300. 400.]
 [ 16. 300. 400. 350. 450.]
 [ 17. 350. 450. 400. 500.]
 [ 18. 400. 500. 450. 550.]
 [ 19. 450. 550. 500. 600.]
 [ 20. 500. 600. 550. 650.]
 [ 21. 550. 650. 600. 700.]
 [ 22. 600. 700. 650. 750.]
 [ 23. 700. 800. 750. 850.]
 [ 24. 400. 500. 450. 550.]
 [ 25. 450. 550. 500. 600.]
 [ 26. 500. 600. 550. 650.]
 [ 27. 550. 650. 600. 700.]
 [ 28. 600. 700. 650. 750.]
 [ 29. 700. 800. 750. 850.]
 [ 30. 550. 650. 600. 700.]
 [ 31. 600. 700. 650. 750.]
 [ 32. 700. 800. 750. 850.]]


In [46]:
index_col = (dat.shape[0])
index_col

33

In [47]:
index = np.arange(index_col)
print(index)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32]


dat.shape[0] returns the number of rows in the dat array, 

dat.shape[1] returns the number of columns in the dat array,

#To stack these arrays vertically, we would use np.concatenate() with axis=0, like this:
#To stack these arrays vertically, we would use np.concatenate() with axis=1, like this:

When we say "stacking arrays along the second axis", we mean that we are concatenating the arrays horizontally, such that the columns of one array
are appended to the right of the columns of another array. 
In other words, we are stacking the arrays "side by side".

In [88]:
# stack vertically

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

c = np.concatenate((a, b), axis=0)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [93]:
# stack horizontally


import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

c = np.concatenate((a, b), axis=1)
c

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [2]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.vstack((a,b))
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
import numpy as np

a = np.array([[1, 2, 3], 
              [4, 5, 6]])

b = np.array([[7, 8, 9], 
              [10, 11, 12]])

c = np.hstack((a,b))
print(c)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


hstack to join numpy arrays horizontally(axis = 1), 
When we say "stacking arrays along the second axis", we mean that we are concatenating 
the arrays horizontally, such that the columns of one array are appended to the right of
the columns of another array. In other words, 
we are stacking the arrays "side by side".

In [92]:
import numpy as np
dat = np.loadtxt('C:/Users/pawar/Videos/data.txt', delimiter=',')
d = np.array([[1,2,3,4,5]])
r = np.array([[6,7,8,9,67]])
a = np.hstack((d,r))
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 67]])

In [94]:
import numpy as np
dat = np.loadtxt('C:/Users/pawar/Videos/data.txt', delimiter=',')
d = np.array([[1,2,3,4,5]])
r = np.array([[6,7,8,9,67]])
a = np.vstack((d,r))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 67]])

why we are processing the image
There are many reasons why we process images, including:

Enhancing the quality of the image: Image processing techniques can be used to improve the quality of an image, such as removing noise, adjusting brightness and contrast, and sharpening edges.

Extracting useful information: Image processing can help extract useful information from an image, such as identifying objects or patterns, detecting features, and measuring properties of the image.

Compression: Images can be compressed using image processing techniques to reduce their file size while maintaining image quality. This is useful for storing and transmitting large amounts of image data more efficiently.

Image recognition and computer vision: Image processing techniques are used extensively in computer vision and image recognition applications, such as face recognition, object detection, and autonomous vehicles.

Artistic effects: Image processing techniques can also be used for artistic purposes, such as applying filters, creating collages, and modifying colors.

Overall, image processing is a powerful tool that can be used to manipulate, enhance, and extract useful information from images, making them more useful and informative in a wide range of applications.

In [2]:
import cv2
import numpy as np
img = cv2.imread(r'D:\DEEP_CERTIFICATE\photo (2).png', cv2.IMREAD_GRAYSCALE)
cv2.imshow('photo (2).png', img)
# resized_img = cv2.resize(img, (500, 500))  # Resize to a fixed size
# cv2.imshow('Image', resized_img)
s = np.array(img)
print(s)
cv2.waitKey(0)
cv2.destroyAllWindows()





[[186 178 175 ... 182 182 182]
 [186 178 175 ... 183 182 182]
 [186 180 179 ... 182 182 182]
 ...
 [173 170 175 ...  61  34  68]
 [171 169 174 ...  66  39  68]
 [173 171 176 ...  64  34  66]]


In [7]:
np.shape(s)

(757, 615)

In [10]:
d = np.sum(s,axis = 0)
d

array([127209, 127351, 127304, 127239, 127521, 127624, 127598, 127476,
       127654, 127593, 127371, 127100, 127187, 127215, 127119, 127101,
       126945, 126685, 126398, 126371, 126254, 126291, 125664, 123718,
       119915, 114098, 110959, 112344, 112849, 112727, 112506, 112455,
       112450, 112146, 112051, 112062, 112043, 111627, 111571, 111609,
       111700, 111654, 111748, 111842, 111852, 111655, 111493, 111745,
       111688, 111733, 111725, 111583, 111506, 111623, 111224, 111192,
       111219, 111116, 111088, 111042, 111149, 111176, 111080, 110905,
       111067, 111189, 111382, 111160, 110976, 110979, 110963, 110900,
       110851, 110784, 110625, 110523, 110656, 110551, 110426, 110413,
       110286, 110454, 110541, 110329, 110171, 110119, 110184, 110264,
       110165, 109820, 109757, 109768, 109699, 109674, 109733, 109712,
       109474, 109703, 109819, 109580, 109347, 109598, 110036, 110001,
       109931, 109660, 109690, 109467, 109301, 109188, 109136, 108736,
      

What is computer vision? Computer vision is a field of artificial intelligence (AI) 
that enables computers and systems to derive meaningful information from digital images, 
videos and other visual inputs — and
take actions or make recommendations based on that information.


In [18]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

intersection = np.union1d(a, b)
print(intersection)

[1 2 3 4 5 6 7]


The union of two sets is a set that contains all the elements that are in either set. In other words, the union of two sets is the combination of all elements from both sets, without any duplicates.

The intersection of two sets is a set that contains all the elements that are common to both sets. In other words, the intersection of two sets is the set of elements that are present in both sets.

In [19]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

intersection = np.intersect1d(a, b)
print(intersection)

[3 4 5]


In [20]:
import numpy as np

a = np.array([[1, 2, 3],
              [2,3,4]])

b = np.array([[3, 4, 5],
              [8,9,7]])

print(a)
print()
print(b)
print()
intersection = np.intersect1d(a, b)
print(intersection)

[[1 2 3]
 [2 3 4]]

[[3 4 5]
 [8 9 7]]

[3 4]


In [22]:
print(np.mean(a))

2.5


In [23]:
15/6

2.5

### Standard Deviation

In [33]:
print(np.std(a))

0.9574271077563381


The formula for the standard deviation is:

Standard deviation (σ) = sqrt[ Σ(x - μ)² / N ]

where:

x is each data point in the dataset
μ is the mean (average) of the dataset
N is the total number of data points in the dataset.

----------------------------------------------------------

Calculate the mean of the data:

Mean = (1+2+3+2+3+4)/6 = 2.5

Calculate the difference between each data point and the mean:

For the first row: (1-2.5), (2-2.5), (3-2.5)

For the second row: (2-2.5), (3-2.5), (4-2.5)

These differences are: -1.5, -0.5, 0.5, -0.5, 0.5, 1.5

Calculate the square of each difference:

(-1.5)^2, (-0.5)^2, (0.5)^2, (-0.5)^2, (0.5)^2, (1.5)^2

These values are: 2.25, 0.25, 0.25, 0.25, 0.25, 2.25

(2.25+0.25+0.25+0.25+0.25+2.25)/6 = 0.92666

import math
math.sqrt(0.92666)

ans is 0.962


In [34]:
print(np.median(a))

2.5


In [27]:
arr = np.save("saving by name",a)
loads = np.load('saving by name.npy')

In [28]:
loads

array([[1, 2, 3],
       [2, 3, 4]])

In [29]:
(2.25+0.25+0.25+0.25+0.25+2.25)/6

0.9166666666666666

In [35]:
import math
math.sqrt(0.92666)

0.9626318091565436